use_frameworks!
inhibit_all_warnings!

target 'Constraint_Example' do
  pod 'Constraint', :path => '../'

  target 'Constraint_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
